@extends('layouts.app')

@section('title', 'Звіт - презентація міського голови')

@section('css_import')
    @parent
    <link rel="stylesheet" href="{{ asset('/css/report_presentation.css') }}">
@endsection

@section('javascript_import')
    @parent
    <script src="{{ asset('/js/report_presentation.js') }}"></script>
@endsection

@php
    function transliteration($s) {
    $s = (string) $s;
    $s = trim($s);
    $s = function_exists('mb_strtolower') ? mb_strtolower($s) : strtolower($s); // переводим строку в нижний регистр (иногда надо задать локаль)
    $s = strtr($s,[
      'а'=>'a','б'=>'b','в'=>'v','г'=>'g',
      'ґ'=>'g','д'=>'d','е'=>'e','є'=>'ye','ж'=>'j',
      'з'=>'z','и'=>'y','і'=>'i','ї'=>'yi','й'=>'y',
      'к'=>'k','л'=>'l','м'=>'m','н'=>'n','о'=>'o',
      'п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u',
      'ф'=>'f','х'=>'h','ц'=>'c','ч'=>'ch','ш'=>'sh',
      'щ'=>'shch','ю'=>'yu','я'=>'ya','ь'=>'', '`'=>'',
      ' '=>'_', '-'=>'_', '\''=>'', ',' => '', '.' => '',
    ]);
    return $s;
    }

    $breadcrumbs = [
     [
         'name' => 'Перелік звітів',
         'url' => 'list_of_reports',
     ],
     [
         'name' => '2020',
         'url' => 'report_2020',
     ],
     [
         'name' => 'Презентація',
     ]
    ];

/*
 *
[
    'name' => '',
    'img' => '',
    'img_stretch' => 'vertical',
    'content' => '',
    'subparagraphs' => [],
],

 */
    $presentation = [
        [
            'name' => 'Виконання бюджету громади та фінансова політика у 2020 році',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 37.8px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Виконання бюджету громади та фінансова політика у 2020 році </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Аналіз економічного та соціального розвитку Луцької міської територіальної громади у 2020 році та діяльність департаменту економічної політики',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Аналіз економічного та соціального розвитку Луцької міської територіальної громади у 2020 році та діяльність департаменту економічної політики </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Розвиток підприємництва та сфери зовнішньої реклами',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Розвиток підприємництва та сфери зовнішньої реклами </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Розвиток міського пасажирського транспорту',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Розвиток міського пасажирського транспорту </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Житлово-комунальне господарство та благоустрій міста',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Житлово-комунальне господарство та благоустрій міста </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Діяльність відділу екології',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Діяльність відділу екології </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Основні підсумки діяльності департаменту муніципальної варти',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Основні підсумки діяльності департаменту муніципальної варти </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Містобудівна діяльність, капітальне будівництво  та забезпечення архітектурно-будівельного контролю',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Містобудівна діяльність, капітальне будівництво та забезпечення архітектурно-будівельного контролю </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Управління майном міської комунальної власності та земельними ресурсами',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Управління майном міської комунальної власності та земельними ресурсами </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Соціальна  політика та соціальний захист населення громади',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Соціальна політика та соціальний захист населення громади </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Розвиток галузі охорони здоров’я',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Розвиток галузі охорони здоров’я </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Про роботу освітньої галузі у 2020 році',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 32.4px; width: 756px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Про роботу освітньої галузі у 2020 році </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 1080px; height: 42px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 20.52px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 62px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 15.12px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 67px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 335px; height: 69px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Соціальний захист дорослих, дітей та підлітків вразливих категорій громадян',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Соціальний захист дорослих, дітей та підлітків вразливих категорій громадян </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Діяльність департаменту сім’ї, молоді та спорту',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Діяльність департаменту сім’ї, молоді та спорту </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Розвиток галузі культури',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Розвиток галузі культури </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Розвиток галузі туризму та промоція міста',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Розвиток галузі туризму та промоція міста </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Міжнародна та проектна діяльність міської ради',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Міжнародна та проектна діяльність міської ради </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Основні підсумки роботи Центру надання адміністративних послуг у місті Луцьку та розгляд звернень громадян',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Основні підсумки роботи Центру надання адміністративних послуг у місті Луцьку та розгляд звернень громадян </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Робота загального відділу міської ради',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Робота загального відділу міської ради </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Робота депутатського корпусу та відділу секретаріату міської ради',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Робота депутатського корпусу та відділу секретаріату міської ради </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Робота відділу зв’язків з громадськістю',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Робота відділу зв’язків з громадськістю </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Робота відділу ведення державного реєстру виборців',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Робота відділу ведення державного реєстру виборців </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
        [
            'name' => 'Діяльність відділу кадрової роботи і нагород міської ради',
            'img' => '/img/slides/2020/0.jpg',
            'img_stretch' => 'vertical',
            'content' => ' <span cy="45%" cx="50%" widthmultiplier="70" fontsizemultiplier="3" height="auto" canchor="-50%,-50%" style="text-align: center; font-size: 23.4px; width: 546px; position: absolute; top: 45%; left: 50%; transform: translate(-50%, -50%);"> Діяльність відділу кадрової роботи і нагород міської ради </span> <div widthmultiplier="100" heightmultiplier="5.5" cy="3.8%" cx="0%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgb(27, 100, 235)); width: 780px; height: 31px; position: absolute; top: 3.8%; left: 0%;" class="shadow"> <a cx="10%" cy="46%" canchor="-50%,-50%" style="color: white; text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 10%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.lutskrada.gov.ua"> #lutskrada.gov.ua </a> <a cx="92%" cy="46%" canchor="-50%,-50%" style="color: rgb(255, 255, 255); text-decoration: none; font-weight: 700; width: fit-content; font-size: 14.82px; position: absolute; top: 46%; left: 92%; transform: translate(-50%, -50%);" fontsizemultiplier="1.9" href="https://www.facebook.com/lutskrada"> fb:@lutskrada </a> </div> <img cy="87%" cx="39%" canchor="-50%, -50%" heightmultiplier="8" src="img/Herb_Lutsk.svg" alt="" style="height: 45px; position: absolute; top: 87%; left: 39%; transform: translate(-50%, -50%);"> <span fontsizemultiplier="1.4" cy="86.8%" cx="45.5%" canchor="-50%, -50%" style="font-weight: bold; font-size: 10.92px; position: absolute; top: 86.8%; left: 45.5%; transform: translate(-50%, -50%);"> ЛУЦЬКА <br> МІСЬКА <br> РАДА </span> <img heightmultiplier="8.7" cx="59%" cy="87%" canchor="-50%, -50%" src="img/logo_lutsk.png" alt="" style="height: 49px; position: absolute; top: 87%; left: 59%; transform: translate(-50%, -50%);"> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="100%" canchor="-100%,-50%" style="background: linear-gradient(to left, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 100%; transform: translate(-100%, -50%);"> </div> <div widthmultiplier="31" heightmultiplier="9" cy="87%" cx="0%" canchor="0%,-50%" style="background: linear-gradient(to right, rgb(255, 0, 0), 50%, rgba(0, 255, 255, 0)); width: 242px; height: 50px; position: absolute; top: 87%; left: 0%; transform: translate(0%, -50%);"> </div> <section> <style> </style> <script> </script> </section> ',
            'subparagraphs' => [],
        ],
    ];
    /*
     * fixing an article's content depends on needed corrections (__slide_id__ transform to actual slide id, etc)
     */
    $replacementPatterns = [
        'idReplacementPattern' => '/__slide_id__/mi',
        'imageSrcReplacementPattern' => '/(<\s*img.*?src\s*=\s*")(.*?)(\s*".*?>)/mi'
    ];

    foreach($presentation as $key => $slide) {

        if (!empty($slide['subparagraphs'])) {
            foreach($slide['subparagraphs'] as $subKey => $subparagraph) {
                $presentation[$key]['subparagraphs'][$subKey]['content'] = preg_replace($replacementPatterns,
                [

                    transliteration($subparagraph['name']), //idReplacementPattern
                    '$1'.asset('$2').'$3', //imageSrcReplacementPattern

                ], $subparagraph['content']);
                 $presentation[$key]['subparagraphs'][$subKey]['img'] = asset($subparagraph['img']);
            }
        }

         $presentation[$key]['content'] = preg_replace($replacementPatterns,
        [

            transliteration($slide['name']), //idReplacementPattern
            '$1'.asset('$2').'$3', //imageSrcReplacementPattern

        ], $slide['content']);
        $presentation[$key]['img'] = asset($slide['img']);
    }
@endphp

@section('content')
    <script>
        /* Array with php values, which has been transferred through side.blade.php file.
        * This array exists because sometimes we need to get access to them from imported
        * internal content into slides through $content variable*/

        let slidesVariables = []
    </script>

    <div class="presentation-and-menu-container">
        <button class="menu-button col-12 shadow">
            Зміст
        </button>
        <div class="col-12 col-md-5 col-lg-4 col-xl-3 shadow menu-container">
            <div class="row mb-3 d-flex justify-content-center">
                @include('includes.breadcrumb', ['breadcrumbs' => $breadcrumbs])
                <button class="menu-button menu-button-inline mt-2 col-11">
                    Сховати
                </button>
            </div>
            <nav id="presentation">
                <nav class="nav nav-pills flex-column">
                    @foreach($presentation as $slide)

                        @if($loop->first)
                            <a class="nav-link main-paragraph active"
                               href="#{{ transliteration($slide['name']) }}">{{ $slide['name'] }}</a>
                            @continue
                        @endif

                        <a class="nav-link main-paragraph"
                           href="#{{ transliteration($slide['name']) }}">{{ $slide['name'] }}</a>

                        @if(isset($slide['subparagraphs']) && !empty($slide['subparagraphs']))
                            @foreach($slide['subparagraphs'] as $subparagraph)

                                @if($loop->first)
                                    <nav class="nav nav-pills flex-column">
                                        <a class="nav-link ms-4"
                                           href="#{{ transliteration($subparagraph['name']) }}">{{ $subparagraph['name'] }}</a>
                                        @continue
                                        @endif
                                        @if($loop->last)
                                            <a class="nav-link ms-4"
                                               href="#{{ transliteration($subparagraph['name']) }}">{{ $subparagraph['name'] }}</a>
                                    </nav>
                                    @break
                                @endif
                                <a class="nav-link ms-4"
                                   href="#{{ transliteration($subparagraph['name']) }}">{{ $subparagraph['name'] }}</a>
                            @endforeach
                        @endif
                    @endforeach
                </nav>
            </nav>
        </div>
        <div class="col-12 col-md-7 col-lg-8 col-xl-9">
            <div data-bs-spy="scroll" data-bs-target="#presentation"
                 data-bs-offset="100"
                 class="presentation-container" tabindex="0">
                @foreach($presentation as $slide)
                    @include('includes.slide',
                                    [
                                        'id' => transliteration($slide['name']),
                                        'img' => $slide['img'],
                                        'content' => $slide['content'],
                                        'img_stretch' => $slide['img_stretch'],
                                    ])

                    @if(isset($slide['subparagraphs']) && !empty($slide['subparagraphs']))
                        @foreach($slide['subparagraphs'] as $subparagraph)
                            @include('includes.slide',
                                [
                                    'id' => transliteration($subparagraph['name']),
                                    'img' => $subparagraph['img'],
                                    'content' => $subparagraph['content'],
                                    'img_stretch' => $subparagraph['img_stretch'],
                                ])
                        @endforeach
                    @endif

                @endforeach
            </div>
        </div>
    </div>
@endsection
